{;
    int y = 1000; 
    int x = ( 100 + 200 ) - 3 * y; 
    {;
        int z = 2000; 
        {;
            int j = z + x + y; 
            {;
                int i = j * 1000 + 2000 - y; 
                {;
                    int m = i * j; 
                    {;
                        int total = x + y + z + j + i + m; 
                        CRC_OUT x; 
                        CRC_OUT y; 
                        CRC_OUT z; 
                        CRC_OUT j; 
                        CRC_OUT i; 
                        CRC_OUT m; 
                        CRC_OUT total; 
                    };
                };
            };
        };
    };
};


void main() {;
};